PyYAML==6.0
requests==2.26.0
jsonschema==3.2.0
web3==5.24.0
eth-abi==1.2.0

# Development dependencies
pytest==7.3.1
black==23.3.0
flake8==6.0.0
mypy==1.3.0

# Security analysis
slither-analyzer==0.9.3
mythril==0.23.15
